services:
  - type: web
    name: legacynet
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USER
        value: your_email@gmail.com
      - key: EMAIL_PASS
        value: your_app_password
